# Generated by Django 4.1.3 on 2023-10-07 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("work_environment", "0002_workenvironment_created_by"),
        ("video", "0002_alter_video_unique_together_video_work_environment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="work_environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="created_by_video",
                to="work_environment.workenvironment",
                verbose_name="Entorno de Desarrollo",
            ),
        ),
    ]
