# Generated by Django 4.1.3 on 2023-10-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("work_environment", "0002_workenvironment_created_by"),
        ("video", "0003_alter_video_work_environment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="work_environment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="work_environment_video",
                to="work_environment.workenvironment",
                verbose_name="Entorno de Desarrollo",
            ),
            preserve_default=False,
        ),
    ]
