# Generated by Django 4.1.3 on 2023-10-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0004_alter_video_work_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="label",
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="label_name",
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
