# Generated by Django 4.1.3 on 2023-10-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0005_video_label_video_label_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="label_name",
            field=models.CharField(max_length=60, verbose_name="Nombre de la etiqueta"),
        ),
    ]
