# Generated by Django 4.1.3 on 2023-10-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0006_alter_video_label_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="label",
            field=models.PositiveIntegerField(verbose_name="Etiqueta"),
        ),
    ]
