# Generated by Django 4.1.3 on 2023-10-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0008_alter_video_label_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="label",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Etiqueta"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="label_name",
            field=models.CharField(
                default=None, max_length=60, verbose_name="Nombre de la etiqueta"
            ),
            preserve_default=False,
        ),
    ]
