# Generated by Django 4.1.3 on 2023-10-07 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work_environment", "0002_workenvironment_created_by"),
        ("video", "0009_alter_video_label_alter_video_label_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="video",
            unique_together={("label_name", "work_environment")},
        ),
    ]
