# Generated by Django 4.1.3 on 2023-10-07 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0010_alter_video_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="name",
        ),
    ]
