# Generated by Django 4.1.3 on 2023-10-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0011_remove_video_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="label",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Etiqueta"
            ),
        ),
    ]
