# Generated by Django 4.1.3 on 2023-10-07 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0013_video_number_samples"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="label_name",
            field=models.CharField(
                max_length=60,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9_]*$",
                        "Solo se permiten letras, números, guiones y guiones bajos.",
                    )
                ],
                verbose_name="Nombre de la etiqueta",
            ),
        ),
    ]
