# Generated by Django 4.1.3 on 2023-10-04 04:20

import uuid

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Nombre de la suscripción",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Descripción de la suscripción",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Orden"
                    ),
                ),
                (
                    "limit_audios",
                    models.PositiveIntegerField(verbose_name="Límite de audios"),
                ),
                (
                    "limit_images",
                    models.PositiveIntegerField(verbose_name="Límite de imagenes"),
                ),
                (
                    "limit_split_musics",
                    models.PositiveIntegerField(
                        verbose_name="Límite de músicas convertidas"
                    ),
                ),
            ],
            options={
                "verbose_name": 'Registro "Suscripción"',
                "verbose_name_plural": 'Tabla de registros "Suscripción"',
                "db_table": "subscription",
            },
        ),
    ]
