# Generated by Django 4.1.3 on 2023-10-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="order",
            field=models.PositiveIntegerField(default=None, verbose_name="Orden"),
            preserve_default=False,
        ),
    ]
