# Generated by Django 4.1.3 on 2023-10-04 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0002_alter_subscription_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="limit_split_musics",
            new_name="limit_musics",
        ),
    ]
