# Generated by Django 4.1.3 on 2023-11-23 03:44

import apps.models.video_detection.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ia_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetection',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=apps.models.video_detection.models.generate_unique_filename, validators=[apps.models.video_detection.models.validate_video_format], verbose_name='Video')),
                ('video_result', models.FileField(blank=True, editable=False, null=True, upload_to=apps.models.video_detection.models.generate_unique_filename, verbose_name='Resultado del Video')),
                ('ia_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ia_model_video_detection', to='ia_model.iamodel', verbose_name='IAModel')),
            ],
            options={
                'verbose_name': 'Registro "Detección de videos"',
                'verbose_name_plural': 'Tabla de registros "Detección de videos"',
                'db_table': 'video_detection',
            },
        ),
    ]
