# Generated by Django 4.1.3 on 2023-10-08 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ia_model", "0006_alter_iamodel_model_file"),
        ("video_detection", "0002_alter_videodetection_video_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videodetection",
            name="work_environment",
        ),
        migrations.AddField(
            model_name="videodetection",
            name="model_ia",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="work_environment_video_detection",
                to="ia_model.iamodel",
                verbose_name="IAModel",
            ),
            preserve_default=False,
        ),
    ]
