# Generated by Django 4.1.3 on 2023-10-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ia_model", "0008_alter_iamodel_labels_model"),
        ("video_detection", "0003_remove_videodetection_work_environment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videodetection",
            name="model_ia",
        ),
        migrations.AddField(
            model_name="videodetection",
            name="ia_model",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="ia_model_video_detection",
                to="ia_model.iamodel",
                verbose_name="IAModel",
            ),
            preserve_default=False,
        ),
    ]
