# Generated by Django 4.1.3 on 2023-11-23 04:13

import apps.models.project.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.models.project.models.generate_unique_filename, verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Registro "Proyecto"',
                'verbose_name_plural': 'Tabla de registros "Proyecto"',
                'db_table': 'project',
            },
        ),
    ]
