# Generated by Django 4.1.3 on 2023-11-23 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ia_model', '0002_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ia_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='ia_model_project', to='ia_model.iamodel', verbose_name='IAModel'),
            preserve_default=False,
        ),
    ]
