# Generated by Django 4.1.3 on 2023-11-23 04:28

import apps.models.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_ia_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(editable=False, upload_to=apps.models.project.models.generate_unique_filename, verbose_name='Archivo'),
        ),
    ]
