# Generated by Django 4.1.3 on 2023-10-07 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0003_rename_limit_split_musics_subscription_limit_musics"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_user",
                to="subscription.subscription",
                verbose_name="Suscripción",
            ),
        ),
    ]
