# Generated by Django 4.1.3 on 2023-10-07 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("work_environment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workenvironment",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="created_by_work_environment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
            preserve_default=False,
        ),
    ]
