# Generated by Django 4.1.3 on 2023-10-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("work_environment", "0002_workenvironment_created_by"),
        ("ia_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iamodel",
            name="work_environment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="work_environment_ia_model",
                to="work_environment.workenvironment",
                verbose_name="Entorno de Desarrollo",
            ),
            preserve_default=False,
        ),
    ]
