# Generated by Django 4.1.3 on 2023-10-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ia_model", "0003_alter_iamodel_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="iamodel",
            name="model",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="app_imagen/model_files",
                verbose_name="Video",
            ),
        ),
    ]
