# Generated by Django 4.1.3 on 2023-10-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ia_model", "0005_remove_iamodel_model_iamodel_model_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iamodel",
            name="model_file",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                upload_to="app_imagen/model_files/",
                verbose_name="model",
            ),
        ),
    ]
