# Generated by Django 4.1.3 on 2023-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ia_model", "0006_alter_iamodel_model_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="iamodel",
            name="labels_model",
            field=models.TextField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Etiquetas del modelo",
            ),
        ),
    ]
