# Generated by Django 4.1.3 on 2023-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ia_model", "0007_iamodel_labels_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iamodel",
            name="labels_model",
            field=models.JSONField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Etiquetas del modelo",
            ),
        ),
    ]
